### ISSUE TITLE
custom metrics not show as resources in cutom.metrics.k8s.io

### ISSUE THREAD

**Issue by cbryant-zspace** [DirectXMan12/k8s-prometheus-adapter#109]
Using prometheus-adaptor to connect to prometheus v 1.7.0 deployment in k8s on AWS.

One initial issue I had is a missing service that connects the prometheus-url=http://xxx:9090/ to the prometheus deployment instance internal endpoint. Apparently this isn't included in the examples for prometheus nor for the prometheus-adapter.

I have it to the point that scraping of custom metrics is occurring and I can see them directly in prometheus "nodejs_http_requests{instance="10.0.37.12:80",job="pods"}".

I can also see the requests in the log files retrieving the custom metrics from prometheus:
GET http://prometheus-service:9090/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Enodejs_http.%2A%22%7D&amp;start=1536796239.978 200 OK
I0912 23:51:09.982198       1 api.go:93] Response Body: {"status":"success","data":[{"__name__":"nodejs_http_requests","instance":"10.0.37.12:80","job":"pods"}]}

Then the attempt to expose the custom metrics:
Set available metric list from Prometheus to: [[] [] [] [] [] [] [{nodejs_http_requests {instance="10.0.37.12:80", job="pods"}}]]

But "kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1" shows no resources: "{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}"

I suspect it is a permissions issue, but am not clear on which role is used by prometheus-adapter to expose these metrics.

**Comment by cbryant-zspace** [comment]
Perhaps it is related to?

I0913 16:58:00.111007       1 request.go:897] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/","verb":"get"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":false}}

I0913 16:58:04.066274       1 request.go:897] Request Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/swagger.json","verb":"get"},"user":"system:aggregator","group":["system:authenticated"]},"status":{"allowed":false}}

**Comment by DirectXMan12** [comment]
For posterity -- this was discussed on slack, and it looks like it's due to incorrect metrics labeling.  Closing.
