### ISSUE TITLE
[suggestion] Docker image release with log level for metric_namer

### ISSUE THREAD

**Issue by rccrdpccl** [DirectXMan12/k8s-prometheus-adapter#111]
First of all, thank you for all your work @DirectXMan12, it's really useful.

I have notice that the currently tagged docker image (v0.2.1) has a very verbose output, which in our case generated an immense amount of logs to the point of being dangerous (filling up the logging server, which has *a lot* of space).
Of course we can workaround this issue by renaming your latest image (or build our own) and tag it in our registry, however I think this would be nice to have a tagged image which this behaviour, so that people are not encouraged to use latest tag (which also caused more serious problems to us in the past, with the breaking changes).

Do you think it would be possible to release more frequently, especially when there are significant improvements like the logging level for metric_namer.go?

Thanks in advance!

**Comment by DirectXMan12** [comment]
Yeah, I'll tag a release.

**Comment by DirectXMan12** [comment]
https://github.com/DirectXMan12/k8s-prometheus-adapter/releases/tag/v0.2.2
