### ISSUE TITLE
Autoscale based on node metrics exposed to Prometheus by Node exporter

### ISSUE THREAD

**Issue by swatisehgal** [DirectXMan12/k8s-prometheus-adapter#123]
I am trying to access the values of node metrics (exposed by node exporter to Prometheus) in custom metrics API which appear e.g. jobs.batch/node_memory_MemTotal. But when I do kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/batch.jobs/node_memory_MemTotal" | jq . I get Error from server (NotFound): the server could not find the requested resource

**Comment by swatisehgal** [comment]
When I run  kubectl get --raw "/apis/custom.metrics.k8s.io/batch/v1beta1" | jq . I see the following metrics but am unable to access their values
{                                                                                              
      "name": "jobs.batch/node_memory_MemTotal",                                                   
      "singularName": "",                                                                          
      "namespaced": false,                                                                         
      "kind": "MetricValueList",                                                                   
      "verbs": [                                                                                   
        "get"                                                                                      
      ]                                                                                            
    },   
 {                                                                                              
      "name": "jobs.batch/node_netstat_TcpExt_TCPHPHits",                                          
      "singularName": "",                                                                          
      "namespaced": false,                                                                         
      "kind": "MetricValueList",                                                                   
      "verbs": [                                                                                   
        "get"                                                                                      
      ]                                                                                            
    },                                                                                             
    {
      "name": "jobs.batch/node_netstat_TcpExt_TCPReqQFullDrop",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "jobs.batch/node_netstat_Icmp6_InEchoReplies",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }

**Comment by swatisehgal** [comment]
I referred to kubernetes-incubator/metrics-server#90 (comment) in the issue kubernetes-incubator/metrics-server#90 but wasn't able to access the metric values

**Comment by DirectXMan12** [comment]
The reason they're getting exposed as `batch.jobs` is most likely becaues Prometheus is injecting the "job" label, which the adapter is guessing means the Kubernetes `Job` kind, due to the default configuration.  For any metrics exposed via the custom metrics API, you'll need to make sure there's a label whose value corresponds to the object name.  For instance, if you want to talk about node metrics, you'll need some label whose name corresponds to node name.  You can then configure the adapter to recognize that label.

If you provide an example of a series you want to expose, I can provide a more specific example.

**Comment by swatisehgal** [comment]
Here is my prometheus config. Right at the end there is node exporter job which is exposing node metrics and I would like to query those metrics as part of custom metrics api
`---
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: prometheus
  name: prometheus-config
  #namespace: custom-metrics
data:
  prometheus.yml: |

    # A scrape configuration for running Prometheus on a Kubernetes cluster.
    # This uses separate scrape configs for cluster components (i.e. API server, node)
    # and services to allow each to use different authentication configs.
    #
    # Kubernetes labels will be added as Prometheus labels on metrics via the
    # `labelmap` relabeling action.
    #
    # If you are using Kubernetes 1.7.2 or earlier, please take note of the comments
    # for the kubernetes-cadvisor job; you will need to edit or remove this job.

    # Scrape config for API servers.
    #
    # Kubernetes exposes API servers as endpoints to the default/kubernetes
    # service so this uses `endpoints` role and uses relabelling to only keep
    # the endpoints associated with the default/kubernetes service using the
    # default named port `https`. This works for single API server deployments as
    # well as HA API server deployments.
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 1m

    scrape_configs:
    - job_name: 'kubernetes-apiservers'

      kubernetes_sd_configs:
      - role: endpoints

      # Default to scraping over https. If required, just disable this or change to
      # `http`.
      scheme: https

      # This TLS & bearer token file config is used to connect to the actual scrape
      # endpoints for cluster components. This is separate to discovery auth
      # configuration because discovery & scraping are two separate concerns in
      # Prometheus. The discovery auth config is automatic if Prometheus runs inside
      # the cluster. Otherwise, more config options have to be provided within the
      # <kubernetes_sd_config>.
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        # If your node certificates are self-signed or use a different CA to the
        # master CA, then disable certificate verification below. Note that
        # certificate verification is an integral part of a secure infrastructure
        # so this should only be disabled in a controlled environment. You can
        # disable certificate verification by uncommenting the line below.
        #
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      # Keep only the default/kubernetes service endpoints for the https port. This
      # will add targets for each API server which Kubernetes adds an endpoint to
      # the default/kubernetes service.
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https

    # Scrape config for nodes (kubelet).
    #
    # Rather than connecting directly to the node, the scrape is proxied though the
    # Kubernetes apiserver.  This means it will work if Prometheus is running out of
    # cluster, or can't connect to nodes for some other reason (e.g. because of
    # firewalling).
    - job_name: 'kubernetes-nodes'

      # Default to scraping over https. If required, just disable this or change to
      # `http`.
      scheme: https

      # This TLS & bearer token file config is used to connect to the actual scrape
      # endpoints for cluster components. This is separate to discovery auth
      # configuration because discovery & scraping are two separate concerns in
      # Prometheus. The discovery auth config is automatic if Prometheus runs inside
      # the cluster. Otherwise, more config options have to be provided within the
      # <kubernetes_sd_config>.
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: 10.237.222.87:8081
        #replacement: 10.254.144.52:9100
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics
      #static_configs:
      #- targets: ['10.254.144.52:9100']
    # Scrape config for Kubelet cAdvisor.
    #
    # This is required for Kubernetes 1.7.3 and later, where cAdvisor metrics
    # (those whose names begin with 'container_') have been removed from the
    # Kubelet metrics endpoint.  This job scrapes the cAdvisor endpoint to
    # retrieve those metrics.
    #
    # In Kubernetes 1.7.0-1.7.2, these metrics are only exposed on the cAdvisor
    # HTTP endpoint; use "replacement: /api/v1/nodes/${1}:4194/proxy/metrics"
    # in that case (and ensure cAdvisor's HTTP server hasn't been disabled with
    # the --cadvisor-port=0 Kubelet flag).
    #
    # This job is not necessary and should be removed in Kubernetes 1.6 and
    # earlier versions, or it will cause the metrics to be scraped twice.
    - job_name: 'kubernetes-cadvisor'

      # Default to scraping over https. If required, just disable this or change to
      # `http`.
      scheme: https

      # This TLS & bearer token file config is used to connect to the actual scrape
      # endpoints for cluster components. This is separate to discovery auth
      # configuration because discovery & scraping are two separate concerns in
      # Prometheus. The discovery auth config is automatic if Prometheus runs inside
      # the cluster. Otherwise, more config options have to be provided within the
      # <kubernetes_sd_config>.
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

      kubernetes_sd_configs:
      - role: node

      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: 10.237.222.87:8081
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

    # Scrape config for service endpoints.
    #
    # The relabeling allows the actual service scrape endpoint to be configured
    # via the following annotations:
    #
    # * `prometheus.io/scrape`: Only scrape services that have a value of `true`
    # * `prometheus.io/scheme`: If the metrics endpoint is secured then you will need
    # to set this to `https` & most likely set the `tls_config` of the scrape config.
    # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
    # * `prometheus.io/port`: If the metrics are exposed on a different port to the
    # service then set this appropriately.

    # Example scrape config for pods
    #
    # The relabeling allows the actual pod scrape endpoint to be configured via the
    # following annotations:
    #
    # * `prometheus.io/scrape`: Only scrape pods that have a value of `true`
    # * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
    # * `prometheus.io/port`: Scrape the pod on the indicated port instead of the
    # pod's declared ports (default is a port-free target if none are declared).
    - job_name: 'kubernetes-pods'
      # if you want to use metrics on jobs, set the below field to
      # true to prevent Prometheus from setting the `job` label
      # automatically.
      honor_labels: false
      kubernetes_sd_configs:
      - role: pod
      # skip verification so you can do HTTPS to pods
      tls_config:
        insecure_skip_verify: true
      # make sure your labels are in order
      relabel_configs:
      # these labels tell Prometheus to automatically attach source
      # pod and namespace information to each collected sample, so
      # that they'll be exposed in the custom metrics API automatically.
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: pod
      # these labels tell Prometheus to look for
      # prometheus.io/{scrape,path,port} annotations to configure
      # how to scrape
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        #replacement: 10.237.222.87:30999
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scheme]
        action: replace
        target_label: __scheme__
        regex: (.+)
    - job_name: kubernetes-node-exporter
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      scheme: https
      kubernetes_sd_configs:
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: ^(.*):\d+$
        target_label: __address__
        replacement: $1:9100
      - target_label: __scheme__
        replacement: http
      # Host name
      - source_labels: [__meta_kubernetes_node_name]
        target_label: node
`

**Comment by swatisehgal** [comment]
This images shows you the metrics and their labels which includes the name of the node
![image](https://user-images.githubusercontent.com/18619641/48150682-505d8980-e2b7-11e8-8dd1-46d53a30c39a.png)

**Comment by swatisehgal** [comment]
rules:                                                                                                                    
- seriesQuery: '{__name__=~"^container_.*",container_name!="POD",kubernetes_namespace!="",pod_name!=""}'                  
  seriesFilters: []                                                                                                       
  resources:                                                                                                              
    overrides:                                                                                                            
      kubernetes_namespace:                                                                                               
        resource: namespace                                                                                               
      pod_name:                                                                                                           
        resource: pod                                                                                                     
  name:                                                                                                                   
    matches: ^container_(.*)_seconds_total$                                                                               
    as: ""                                                                                                                
  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[5m]))                                      
    by (<<.GroupBy>>)                                                                                                     
- seriesQuery: '{__name__=~"^container_.*",container_name!="POD",kubernetes_namespace!="",pod_name!=""}'                  
  seriesFilters:                                                                                                          
  - isNot: ^container_.*_seconds_total$                                                                                   
  resources:                                                                                                              
    overrides:                                                                                                            
      kubernetes_namespace:                                                                                               
        resource: namespace                                                                                               
      pod_name:                                                                                                           
        resource: pod                                                                                                     
  name:                                                                                                                   
    matches: ^container_(.*)_total$                                                                                       
    as: ""                                                                                                                
  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}[5m]))                                      
    by (<<.GroupBy>>)                                                                                                     
- seriesQuery: '{__name__=~"^container_.*",container_name!="POD",kubernetes_namespace!="",pod_name!=""}'                  
  seriesFilters:                                                                                                          
  - isNot: ^container_.*_total$                                                                                           
  resources:                                                                                                              
    overrides:                                                                                                            
      kubernetes_namespace:                                                                                               
        resource: namespace                                                                                               
      pod_name:                                                                                                           
        resource: pod                                                                                                     
  name:                                                                                                                   
    matches: ^container_(.*)$                                                                                             
    as: ""                                                                                                                
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>,container_name!="POD"}) by (<<.GroupBy>>)                              
- seriesQuery: '{kubernetes_namespace!="",__name__!~"^container_.*"}'                                                     
  seriesFilters:                                                                                                          
  - isNot: .*_total$                                                                                                      
  resources:
    template: <<.Resource>>
  name:
    matches: ""
    as: ""
  metricsQuery: sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)
- seriesQuery: '{kubernetes_namespace!="",__name__!~"^container_.*"}'
  seriesFilters:
  - isNot: .*_seconds_total
  resources:
    template: <<.Resource>>
  name:
    matches: ^(.*)_total$
    as: ""
  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
- seriesQuery: '{kubernetes_namespace!="",__name__!~"^container_.*"}'
  seriesFilters: []
  resources:
    template: <<.Resource>>
  name:
    matches: ^(.*)_seconds_total$
    as: ""
  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m])) by (<<.GroupBy>>)
- seriesQuery: '{__name__=~"^node_.*",kubernetes_io_name="NodeExporter",kubernetes_namespace!="",job!="",pod!=""}'
  seriesFilters: []
  resources:
    overrides:
      kubernetes_namespace:
        resource: namespace
      pod:
        resource: pod
      job:
        resource: job
  name:
    matches: ^node_(.*)_$
    as: ""
#  metricsQuery: sum(rate(<<.Series>>{<<.LabelMatchers>>}[5m]))
#    by (<<.GroupBy>>)

**Comment by swatisehgal** [comment]
@DirectXMan12 Thanks to your comment I have made some progress. I made changes to the above files and am finally able to see node metrics as part of the api
```

 {
      "name": "nodes/node_netstat_Icmp6_InMLDv2Reports",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "nodes/node_netstat_IcmpMsg_OutType0",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
```

My adapter config looks somethings like this:
```
seriesQuery: '{__name__!~"^container_.*",job="kubernetes-node-exporter",node!=""}'
  seriesFilters: []
  resources:
    template: <<.Resource>>
  name:
    matches: ""
    as: ""
```

However, I still fail to access the node metric url endpoint to get metric values. I am trying something like this
`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/nodes/*/node_memory_Inactive" | jq . `

Any recommendations on this??

**Comment by DirectXMan12** [comment]
So, basically, the OOTB metrics don't try and deal with non-namespaced cases.  Looking at your prometheus screenshot, you probably want something like:

```yaml
- seriesQuery: '{__name__=~"^node_.*",node!=""}'  # match things with a `node` label that start with `node_`
  resources: {overrides: {node: node}}  # the only resource we expose this on is nodes, using the `node` label
  name: {matches: "^node_(.*)$"}  # metrics like node_memory_active become nodes/memory_active in the custom metrics API
  metricsQuery: "sum(<<.Series>>{<<.LabelMatchers>>}) by (<<.GroupBy>>)"  # since this isn't a rate, just aggregate by whatever resource we request it on (i.e. nodes right now)
```

**Comment by DirectXMan12** [comment]
Let me know if that helps out, or if it doesn't work

**Comment by swatisehgal** [comment]
Thanks for the help. I got the adapter working!

**Comment by iftachsc** [comment]
Hello any chance i get help with the same in materics named:
jobs.batch/envoy_http_async_client_rq
scraped from istio. i can see it in kubectl get --raw "/apis/metrics.k8s.io/v1beta1 but when i query for pods using kubectl --raw command i always got 404
i use default adapter chart from stable and it scraped prometheus of istio. it does show all envoy metrics. but cannot get items.

**Comment by MA357151** [comment]
> Hello any chance i get help with the same in materics named:
> jobs.batch/envoy_http_async_client_rq
> scraped from istio. i can see it in kubectl get --raw "/apis/metrics.k8s.io/v1beta1 but when i query for pods using kubectl --raw command i always got 404
> i use default adapter chart from stable and it scraped prometheus of istio. it does show all envoy metrics. but cannot get items.

would u find any solution for this? I am also facing same issue.

**Comment by iftachsc** [comment]
@MA357151 yes. i'm scraping from istio the envoy_http_rq_total which is pod level metrics for RPS. it works great. i can share the yamls of the custom adapter. and how to make prometheus scrape this from istio-telemetry.

**Comment by blaketastic2** [comment]
@iftachsc Can you please share how you did this?

**Comment by blaketastic2** [comment]
For anyone that hits this problem with istio 1.1.x or later, the correct approach is to tell Istio which metrics to scrape from envoy with this new setting: 
https://istio.io/docs/reference/commands/pilot-discovery/#annotations

Docs and descriptions of default stats that are collected can be found here: https://archive.istio.io/v1.1/help/ops/telemetry/envoy-stats/

I've also just put the list here:
```yaml
# default values are
sidecar.istio.io/statsInclusionPrefixes: cluster_manager, listener_manager, http_mixer_filter, tcp_mixer_filter, server, cluster.xds-grpc
```

The annotation should sit next to the `sidecar.istio.io/inject` annotation on your deployments, and should have an additional value added of `http` included in the list in order to get `envoy_http_rq_total` propagating to Istio. Additional values I've seen are:
`cluster.outbound, listener, cluster`

**Comment by kmcrawford** [comment]
@blaketastic2 has this changed?  I've added the `http` to the `sidecar.istio.io/statsInclusionPrefixes`  and still don't see `envoy_http_rq_total` being reported.

Config:
`sidecar.istio.io/statsInclusionPrefixes: http,tcp,cluster.,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc`

**Comment by blaketastic2** [comment]
@kmcrawford Currently working values we use are - `sidecar.istio.io/statsInclusionPrefixes: http,cluster_manager,listener_manager,http_mixer_filter,tcp_mixer_filter,server,cluster.xds-grpc`. Make sure you don't have a typo in the config.

Also, here's the latest documentation link - https://istio.io/docs/ops/configuration/telemetry/envoy-stats/

**Comment by kmcrawford** [comment]
@blaketastic2  I think I found it.  It looks like it's now under `envoy_http_stats_rq_total` vs `envoy_http_rq_total`

**Comment by Kubessandra** [comment]
## This is not working
`
kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/server_app_active_users" | jq 
`
Command not working. 
```
Error from server (NotFound): the server could not find the metric server_app_active_users for pods
```
The config:
```yaml
    resources:
      overrides:
        kubernetes_pod_name:
          resource: pod
```

## This is Working
fixed the issue by overriding the namespace too:
```yaml
    resources:
      overrides:
        kubernetes_pod_name:
          resource: pod
        kubernetes_namespace:
          resource: namespace
```
And now `kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/pods/*/server_app_active_users" | jq ` is good !
