### ISSUE TITLE
Does the adapter work on a regional GKE cluster?

### ISSUE THREAD

**Issue by cdaguerre** [DirectXMan12/k8s-prometheus-adapter#134]
Has anyone managed to setup the prometheus adapter on a [regional GKE cluster](https://cloud.google.com/kubernetes-engine/docs/concepts/regional-clusters)?

When installing the helm chart, the `APIService` is not registered.
```sh
$ kubectl describe apiservice v1beta1.custom.metrics.k8s.io
Name:         v1beta1.custom.metrics.k8s.io
Namespace:    
Labels:       app=prometheus-adapter
              chart=prometheus-adapter-v0.2.0
              heritage=Tiller
              release=prometheus-adapter
Annotations:  <none>
API Version:  apiregistration.k8s.io/v1beta1
Kind:         APIService
Metadata:
  Creation Timestamp:  2018-11-19T09:19:29Z
  Resource Version:    2415470
  Self Link:           /apis/apiregistration.k8s.io/v1beta1/apiservices/v1beta1.custom.metrics.k8s.io
  UID:                 3803d79d-ebdc-11e8-bd39-4201ac10200b
Spec:
  Ca Bundle:                 <nil>
  Group:                     custom.metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       kube-system
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2018-11-19T09:19:29Z
    Message:               no response from https://10.1.0.26:6443: Get https://10.1.0.26:6443: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
    Reason:                FailedDiscoveryCheck
    Status:                False
    Type:                  Available
Events:                    <none>
```

The `prometheus-adapter` service is running fine and reachable from pods. The adapter logs show that healthchecks are working. I tried both self-signed and previously generated certificates. Does this mean there are connectivity issues between the Custer masters and the adapter service? I have other APIservices set up that work fine, eg. certmanager.k8s.io/v1alpha1 for instance.

Kubernetes version: `v1.11.2-gke.18`
Prometheus adapter docker image: `latest` (I tried them all)
Kubernetes Master CIDR range: `172.16.32.0/28`
Kubernetes Services CIDR range: `10.2.0.0/20`
Kubernetes Pod CIDR range: `10.1.0.0/16`

I have firewall rules allowing all egress and ingress traffic between these CIDR ranges.

It seems GCP recommends exporting prometheus metrics to stackdriver and then scale on external metrics but that doesnt seem like a clean efficient way of doing things to me, ref. https://cloud.google.com/kubernetes-engine/docs/tutorials/external-metrics-autoscaling. 

Is the prometheus-adapter just not supported in GKE yet?

**Comment by cdaguerre** [comment]
Ok It took me forever to understand that I had to whitelist the port on which the prometheus-adapter pod listens (not the service) for access from the kubernetes master (eg. [hardcoded 6443 in the official helm chart](https://github.com/helm/charts/blob/6a9f27258c885ea79f2fa949a5fe51ca0e97da10/stable/prometheus-adapter/templates/custom-metrics-apiserver-deployment.yaml#L40))
GKE only whitelists ports 443 and 10250 by default. 
Hope this helps someone else ;)
This helped: https://github.com/kubernetes-incubator/metrics-server/issues/45

**Comment by omarsumadi** [comment]
Hey all - had this problem today.

This is NOT a problem with Prometheus Adapter - as stated above, it is a problem with Google Kubernetes Engine (well, not a problem, just a feature for Cluster Security).

Here's a solution other than tinkering with the helm chart:
gcloud compute firewall-rules create allow-prometheus-adapter \
    --action ALLOW \
    --direction INGRESS \
    --source-ranges 172.16.0.0/28 \ # Master CIDR Block
    --rules tcp:6443 \
    --network {{VPC Network Name}}

**Comment by Dr-Irv** [comment]
If using helm on GKE, here's a solution that involves just changing your helm chart.  In `Chart.yaml`, include dependencies for prometheus:

```yaml
dependencies: 
- name: kube-prometheus-stack
  version: '*'
  repository: https://prometheus-community.github.io/helm-charts
- name: prometheus-adapter
  version: '*'
  repository: https://prometheus-community.github.io/helm-charts
```

 In `values.yaml`, include the following:
```yaml
prometheus-adapter:
  listenPort: 10250
```
Since port 10250 is already whitelisted, no need to change firewall settings.  Tried port 443, but that created a collision.
