### ISSUE TITLE
resource metrics: no pods to fetch metrics for

### ISSUE THREAD

**Issue by brancz** [DirectXMan12/k8s-prometheus-adapter#147]
A cluster that has a namespace with no pods where a request for said namespace is done returns an error along the lines of:

```
Error from server: Error while fetching pod metrics for selector  in namespace "default": no pods to fetch metrics for
```

This is done here: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/7a421bb91e9ea52be4e26db22392c36c8af38bc8/pkg/resourceprovider/provider.go#L122-L124

My feeling is that this shouldn't error, but just return an empty list, and looking at what the [metrics-server does](https://github.com/kubernetes-incubator/metrics-server/blob/ca29d12df6c984c2ed3816772ef92fbb0be16fe5/pkg/provider/sink/sinkprov.go#L80-L119), it seems that that's what is intended.

@DirectXMan12 @squat @s-urbaniak @metalmatze

**Comment by DirectXMan12** [comment]
Yeah, just remove that check
