### ISSUE TITLE
Empty custom metrics API

### ISSUE THREAD

**Issue by okrasnyiblues** [DirectXMan12/k8s-prometheus-adapter#154]
Hi, I'm installing k8s-prometheus-adapter using helm on eks. I've also installed prometheus operator using helm. The problem is when I try to:
`$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1`
I only get:
`  {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"custom.metrics.k8s.io/v1beta1","resources":[]}`

Is there anything else needed to get metrics on eks (I created cluster using eksctl with default values) ?

**Comment by okrasnyiblues** [comment]
@q3aiml

**Comment by DirectXMan12** [comment]
check the logs of the prometheus adapter.  Do they say anything interesting?

**Comment by okrasnyiblues** [comment]
`E1221 09:50:35.850202       1 provider.go:206] unable to update list of all metrics: unable to fetch metrics for query "{__name__=~\"^container_.*\",container_name!=\"POD\",namespace!=\"\",pod_name!=\"\"}": Get http://prometheus.default.svc:9090/api/v1/series?match%5B%5D=%7B__name__%3D~%22%5Econtainer_.%2A%22%2Ccontainer_name%21%3D%22POD%22%2Cnamespace%21%3D%22%22%2Cpod_name%21%3D%22%22%7D&start=1545384635.773: dial tcp: lookup prometheus.default.svc on 10.100.0.10:53: no such host
`

**Comment by okrasnyiblues** [comment]
Solved. URL of prometheus from prometheus-operator wasn't matching with the default in prometheus adapter.
`http://<name of your prometheus operator release>-prometheus-prometheus.<name of your namespace>.svc`
So in case somebody is installing adapter with helm and uses prometheus-operator use: 
`helm install --namespace <name of your namespace> --name my-release --set prometheus.url=http://<name of your prometheus operator release>-prometheus-prometheus.<name of your namespace>.svc stable/prometheus-adapter`
