### ISSUE TITLE
[question] Documentation of --v flag

### ISSUE THREAD

**Issue by carlioth** [DirectXMan12/k8s-prometheus-adapter#155]
I've noticed that I kept getting gigabytes of log data. I had the flag log verbosity set to 10 (--v:10).
I tried to find some documentation of the different levels, but I couldn't find anything. 

Is there any documentation that I'm missing? 
I've now set it to --v:1

**Comment by carlioth** [comment]
Now I see glog is being used for logging. 
If someone else is looking for more info about the flags, you can find it here: http://rpg.ifi.uzh.ch/docs/glog.html

**Comment by metalmatze** [comment]
Normally people use `-v=4` for running production AFAIK.

**Comment by DirectXMan12** [comment]
(10 is usually reserved for super-verbose debug logging)
