### ISSUE TITLE
Kubernetes Autoscaler

### ISSUE THREAD

**Issue by Sanjanare** [DirectXMan12/k8s-prometheus-adapter#165]
Hi ,
I am new to k8s and have a huge confusion on creating HPA for the below query
we have a prometheus query : (sum(jvm_memory_bytes_used{area="heap"}) ) / (sum(jvm_memory_bytes_max{area="heap"}) )

Problem: Need to get that metrics added to prometheus adapter , so custom metrics can check those and we can implement HPA.
and we are getting those metrics from istio-system prometheus (i dnt know if this information helps)

Kops version : 1.13.1
AWS :provider

**Comment by arielb135** [comment]
Hi, follow this tutorial:
https://github.com/arielb135/HPA-with-prometheus-and-RabbitMQ/blob/master/README.md

**Comment by Sanjanare** [comment]
@arielb135 thank you so much i will try that and will let u know

**Comment by Sanjanare** [comment]
@arielb135 just a small confusion where do we need to mention ruleSelector in prometheus helm, is it in value.yaml file?

**Comment by s-urbaniak** [comment]
@Sanjanare I guess you were able to solve you issue?
@DirectXMan12 I guess we can close out this issue.

**Comment by arielb135** [comment]
> @arielb135 just a small confusion where do we need to mention ruleSelector in prometheus helm, is it in value.yaml file?

Sorry i missed the question,
the rule selector is indeed in values.yaml file, the exact line is here:
https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml#L853

In order for prometheus operator to actually find your PrometheusRules - the labels must match, meaning - all labels that you give there must be also in your prometheus rule

**Comment by Sanjanare** [comment]
@s-urbaniak still trying to make it work , will close in a day thank you
