### ISSUE TITLE
Unnecessary "This is queryPart" log line

### ISSUE THREAD

**Issue by Multiply** [DirectXMan12/k8s-prometheus-adapter#188]
Is it needed to log this line here: https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/ff409a0/pkg/naming/metrics_query.go#L213?

It doesn't bring much value, as you can see the generated URL in the following log-message.

If it's needed, can we at least use the log library, to match the same format?

**Comment by s-urbaniak** [comment]
@Multiply thanks for this issue! Indeed, this must have slipped during the PR review! If you don't mind, please submit a PR for this :-)

**Comment by Multiply** [comment]
@s-urbaniak done.
