### ISSUE TITLE
panic: cluster doesn't provide requestheader-client-ca-file

### ISSUE THREAD

**Issue by ngtuna** [DirectXMan12/k8s-prometheus-adapter#19]
Hi @DirectXMan12,

I deploy k8s-prometheus-adapter to minikube via this manifest: https://github.com/luxas/kubeadm-workshop/blob/master/demos/monitoring/custom-metrics.yaml

And it get CrashLoopBackoff. The log is showing:
```
panic: cluster doesn't provide requestheader-client-ca-file
```
Full log: https://gist.github.com/ngtuna/9235afed0d6d14cdd0c7c6e00bb46e05

I don't know if I am doing anything wrong, and I don't really understand why it needs requestheader-client-ca-file. Please help :-)

**Comment by luxas** [comment]
Minikube doesn't support API aggregation OOTB :(
kubeadm does, can you try that?

**Comment by luxas** [comment]
cc @DirectXMan12 we should handle this more gracefully

**Comment by ngtuna** [comment]
@luxas ACK. Thanks for clarifying that. I will try kubeadm/kops instead. Closing this.

**Comment by DirectXMan12** [comment]
@luxas there's not much we can do to handle it more gracefully -- unless you explicitly note that you want to skip requestheader auth, I'd consider not being able to fetch the necessary components a hard failure case.

I've linked the concepts documentation in the upcoming walkthrough (which explains requestheader auth and its role in aggregation), and I'm working to improve the main Kubernetes docs in that regard.

**Comment by DirectXMan12** [comment]
@ngtuna in the mean time, I'd recommend reading through [the aggregated API server concepts documentation](https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/README.md)

**Comment by ngtuna** [comment]
@DirectXMan12 thanks for the reference 👍
