### ISSUE TITLE
LabelValuesByName incorrect value 

### ISSUE THREAD

**Issue by AkashDeepSingh265** [DirectXMan12/k8s-prometheus-adapter#191]
I am using LabelValuesByName in my query . The issue i am facing is when i try to get pod value from it , it is returning me an array instead of string with all the pods name 

Expected 
<<index .LabelValuesByName "pod_name">> 
"pod1|pod2"

Got :
[pod1 pod2]

**Comment by s-urbaniak** [comment]
@AkashDeepSingh265 thanks for filing the issue!

Indeed, internally `LabelValuesByName` is represented as a `map[string][]string`, hence you are getting the string representation of a string slice, in your case `[pod1 pod2]`.

@paulfantom This is a nice exercise to fix, so let's pair on this :-)
