### ISSUE TITLE
avg on a jvm metric just returns empty items

### ISSUE THREAD

**Issue by arunpmohan** [DirectXMan12/k8s-prometheus-adapter#194]
Hey 
My prometheus adapter config is as follows 
custom:
   - seriesQuery: 'jvm_memory_bytes_used{kubernetes_name!="",kubernetes_namespace!=""}'
     resources:
       overrides:
         kubernetes_namespace:
           resource: namespace
         kubernetes_name:
           resource: service
     name:
       matches: "^jvm_memory_bytes_used"
       as: "jvm_memory_bytes_used"
     metricsQuery: "avg(jvm_memory_bytes_used{app=~\".*smp-core.*\",area=\"heap\"}) by (release)"

If i query i get this

 kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/default/services/*/jvm_memory_bytes_used | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/services/%2A/jvm_memory_bytes_used"
  },
  "items": []
}

If i do not do avg function and not grouping by release then everything works ..

**Comment by s-urbaniak** [comment]
@arunpmohan the `avg` function is an aggregation function. The resulting value will only include the labels specified in the `by` clause, in your case only `release`. You also want to add `kubernetes_namespace`, `kubernetes_name` to it so the adapter can associate the result with the configured resources.

**Comment by arunpmohan** [comment]
Got it . Thank you.
