### ISSUE TITLE
Makefile is incompatible with Mac operating system

### ISSUE THREAD

**Issue by liguozhong** [DirectXMan12/k8s-prometheus-adapter#198]
Makefile is incompatible with Mac operating system

Original ：
sed -i "s/BASEIMAGE|$(BASEIMAGE)|g"
After modification：
sed -i "" "s/BASEIMAGE/$(BASEIMAGE)/g"

I Change | into / and add "" after sed -i 。

**Comment by paulfantom** [comment]
Looks like a simple modification. Could you create a PR?
