### ISSUE TITLE
Add vendor folder

### ISSUE THREAD

**Issue by luxas** [DirectXMan12/k8s-prometheus-adapter#2]
@DirectXMan12 Please add the vendor folder and upload to the repo for easier building

**Comment by luxas** [comment]
I can upload that for you as well...

**Comment by DirectXMan12** [comment]
Honestly, I *really* prefer to not have a vendor folder in-repo, which is doable with `glide`.  It makes reviewing much nicer, and makes it possible to mix dep updates in with code changes w/o causing a reviewing headache.

**Comment by DirectXMan12** [comment]
I'd rather just put something in the makefile that runs `glide install -v` if you're missing the `vendor` directory...

**Comment by DirectXMan12** [comment]
resolved in #10 (via the automatic `glide install -v` on changed `glide.lock` or missing `vendor` repository)?  I'm closing this, feel free to re-open if you disagree.
