### ISSUE TITLE
Metrics vs custom metrics

### ISSUE THREAD

**Issue by brian-maloney** [DirectXMan12/k8s-prometheus-adapter#208]
What causes the prometheus-adapter to sometimes serve the metrics.k8s.io API and sometimes serve custom.metrics.k8s.io?  I am trying to get prometheus as provided by coreos/kube-prometheus to serve custom metrics but it always returns NotFound.  Another user was able to resolve the problem by bumping the prometheus-adapter version from 0.4.1 to 0.5.0 (documented [here](https://github.com/coreos/kube-prometheus/issues/108)) but that isn't working for me.  I feel like if I could just understand what's controlling the behavior of what apis the adapter serves I could fix my issue, but I can't find documentation on that anywhere.

Thanks for any help anyone can provide!

**Comment by s-urbaniak** [comment]
@brian-maloney The `metrics.k8s.io` and `custom.metrics.k8s.io` endpoints are gated by different API services. To have prometheus adapter serve custom metrics, you want to register it as a `v1beta1.custom.metrics` API service as shown here:

https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/8c4001831d58edaf66888d4ebb2e105191845ba4/deploy/manifests/custom-metrics-apiservice.yaml#L1-L13

**Comment by brian-maloney** [comment]
@s-urbaniak I have done that, but it still is only trying to serve `metrics.k8s.io` and I am still getting NotFound.

```
bmaloney-mbp:prometheus brian.maloney$ kubectl describe apiservice v1beta1.custom.metrics.k8s.io
Name:         v1beta1.custom.metrics.k8s.io
Namespace:    
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"apiregistration.k8s.io/v1","kind":"APIService","metadata":{"annotations":{},"name":"v1beta1.custom.metrics.k8s.io"},"spec":...
API Version:  apiregistration.k8s.io/v1
Kind:         APIService
Metadata:
  Creation Timestamp:  2019-06-17T14:32:24Z
  Resource Version:    21091403
  Self Link:           /apis/apiregistration.k8s.io/v1/apiservices/v1beta1.custom.metrics.k8s.io
  UID:                 b9058c64-910c-11e9-81d9-42010ac0001b
Spec:
  Group:                     custom.metrics.k8s.io
  Group Priority Minimum:    100
  Insecure Skip TLS Verify:  true
  Service:
    Name:            prometheus-adapter
    Namespace:       monitoring
  Version:           v1beta1
  Version Priority:  100
Status:
  Conditions:
    Last Transition Time:  2019-06-17T14:32:24Z
    Message:               all checks passed
    Reason:                Passed
    Status:                True
    Type:                  Available
Events:                    <none>
bmaloney-mbp:prometheus brian.maloney$ kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1
Error from server (NotFound): the server could not find the requested resource
```

When I curl /apis against the service directly, I get this:

```
root@ubuntu-brian-68d4476bc5-hv2rs:/# curl -k https://prometheus-adapter.monitoring.svc/apis/
{
  "kind": "APIGroupList",
  "groups": [
    {
      "name": "metrics.k8s.io",
      "versions": [
        {
          "groupVersion": "metrics.k8s.io/v1beta1",
          "version": "v1beta1"
        }
      ],
      "preferredVersion": {
        "groupVersion": "metrics.k8s.io/v1beta1",
        "version": "v1beta1"
      },
      "serverAddressByClientCIDRs": [
        {
          "clientCIDR": "0.0.0.0/0",
          "serverAddress": ":6443"
        }
      ]
    }
  ]
}
```

**Comment by brian-maloney** [comment]
One of my colleagues tested this and got it to work with 0.5.0.  We're still not 100% sure exactly why it's working for him but I'm willing to chalk my issues up to some kind of error on my part.  Thank you once again for the help.
