### ISSUE TITLE
Inconsistency with metrics-server in top command 

### ISSUE THREAD

**Issue by JadCham** [DirectXMan12/k8s-prometheus-adapter#211]
Hi,

I noticed an inconsistency between how metrics-server returns container metrics of the pod and the way prometheus-adapter does for `kubectl top pod --containers` command.

We use Spinnaker for CD and it continuously parses the output of `kubectl top` commands to surface them on the UI. It's been complaining about this inconsistency ever since we made the switch from metrics-server. I'm not sure if this is by design in prometheus-adapter (in this case that wouldn't be a bug).

Here is the same pod queried with metrics-server and prometheus-adapter : 

- `metrics-server` 

```
➜  k top po -n monitoring prometheus-prometheus-operator-prometheus-0 --containers 
POD                                           NAME                         CPU(cores)   MEMORY(bytes)
prometheus-prometheus-operator-prometheus-0   prometheus                   36m          539Mi
prometheus-prometheus-operator-prometheus-0   rules-configmap-reloader     0m           1Mi
prometheus-prometheus-operator-prometheus-0   prometheus-config-reloader   0m           2Mi
```

- `prometheus-adapter`
```
➜  k top po -n monitoring prometheus-prometheus-operator-prometheus-0 --containers                                                          
POD                                           NAME                         CPU(cores)   MEMORY(bytes)
prometheus-prometheus-operator-prometheus-0   prometheus                   127m         1749Mi
prometheus-prometheus-operator-prometheus-0   prometheus-config-reloader   0m           4Mi
prometheus-prometheus-operator-prometheus-0   rules-configmap-reloader     0m           2Mi
prometheus-prometheus-operator-prometheus-0                                128m         1756Mi
prometheus-prometheus-operator-prometheus-0   POD
```

**Comment by s-urbaniak** [comment]
@JadCham This rather sounds like a double counting bug :thinking: Can you post the configuration of your resource metrics? Please make sure your resource metrics configuration includes the `container_name!="POD",container_name!="",pod_name!=""` selectors, as in the deployment in the kube-prometheus project:

https://github.com/coreos/kube-prometheus/blob/16a49f00d6c77ad85abbfdba49e186808daf2764/jsonnet/kube-prometheus/prometheus-adapter/prometheus-adapter.libsonnet#L22

We did have a double accounting issue in kube-prometheus which was fixed here https://github.com/coreos/kube-prometheus/commit/df17b1ca3836da4767aab0bb54b412d1df7e85f9

**Comment by JadCham** [comment]
@s-urbaniak I included the selectors and the queries look fine now. Thank You!
