### ISSUE TITLE
Prometheus k8s-prometheus-adapter binary for s390x

### ISSUE THREAD

**Issue by aditijadhav38** [DirectXMan12/k8s-prometheus-adapter#216]
I could see there are binaries available for Prometheus, Prometheus node exporter and Prometheus alertmanager for s390x arch .
Is there any plan to upload binary for k8s-prometheus-adapter?
Link: https://prometheus.io/download/

**Comment by Nayana-ibm** [comment]
Could you please let us know if binaries for collectd-exporter will be available for s390x?

**Comment by s-urbaniak** [comment]
We currently have no plans to include this, but contributions for a s390x based build are very welcome :-)

**Comment by Nayana-ibm** [comment]
@s-urbaniak We have added support for s390x through PR https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/70 and https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/158
We can generate binaries using command "make all ARCH=s390x" (build from source). 

To get binaries for s390x architecture, can we join K8s Prometheus adapter CI?  We can provide s390x vms too. Please let us know.

**Comment by Nayana-ibm** [comment]
@s-urbaniak Could you please let me know if anything needed from my end

**Comment by paulfantom** [comment]
@aditijadhav38 this project is not a part of prometheus GitHub organization, so there is no way to have prometheus-adapter binaries uploaded to prometheus.io/download.

@Nayana-ibm I don't think there is any need for vms with s390x as golang can easily cross-compile to that architecture. Also this application in already published with s390x-ready container images as can be seen by checking docker manifest for `directxman12/k8s-prometheus-adapter` image:
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 739,
         "digest": "sha256:acf4c4dc6aaa51e3004eebdc410b509db45d1a6ebd255457c5745f0b4671678f",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:4ccc54f726f8552499883a0f964b80041a1b689c41682603537f98f1f5a48e80",
         "platform": {
            "architecture": "arm",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:8263840a855ba29d36ff05110e1e392b851b78a2b2cbe0701b4b09dc56b46407",
         "platform": {
            "architecture": "arm64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:807a8971931c702dc6e22805d12fd4a77cac96689d06231d14d087d478f9ca8f",
         "platform": {
            "architecture": "ppc64le",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 740,
         "digest": "sha256:59c3592b41b9f8d0bcbb5bbe470e259494f2465609e84ba7b3836bbadadd4772",
         "platform": {
            "architecture": "s390x",
            "os": "linux"
         }
      }
   ]
}
```

There are no plans on releasing sole binaries which are not containerized.

**Comment by Nayana-ibm** [comment]
@paulfantom Thanks for info and clarification

**Comment by aditijadhav38** [comment]
@paulfantom  Thanks for info.
Closing this issue now
