### ISSUE TITLE
why there is no /apis/custom.metrics.k8s.io/v1beta1 in prometheus-adapter?

### ISSUE THREAD

**Issue by middlestone** [DirectXMan12/k8s-prometheus-adapter#256]
Thanks in advance for anyone who look into this problem.

I am trying to run https://github.com/coreos/kube-prometheus/tree/master/experimental/custom-metrics-api, and use the image https://hub.docker.com/r/directxman12/k8s-prometheus-adapter as the prometheus adapter, but when I run the command below, it doesn't include /apis/custom.metrics.k8s.io/v1beta1, I want to know is this the root cause of apiservice v1beta1.custom.metrics.k8s.io can not contact thee service prometheus-adapter. if yes, how to fix it?

# kubectl get -v=8 --raw /api/v1/namespaces/monitoring/services/https:prometheus-adapter:443/proxy/
I1110 22:15:05.468456   64115 loader.go:359] Config loaded from file:  /etc/kubernetes/admin.conf
I1110 22:15:05.469290   64115 round_trippers.go:416] GET https://10.4.5.117:6443/api/v1/namespaces/monitoring/services/https:prometheus-adapter:443/proxy/
I1110 22:15:05.469311   64115 round_trippers.go:423] Request Headers:
I1110 22:15:05.469325   64115 round_trippers.go:426]     Accept: application/json, */*
I1110 22:15:05.469338   64115 round_trippers.go:426]     User-Agent: kubectl/v1.15.3 (linux/arm64) kubernetes/2d3c76f
I1110 22:15:05.535533   64115 round_trippers.go:441] Response Status: 200 OK in 66 milliseconds
I1110 22:15:05.535568   64115 round_trippers.go:444] Response Headers:
I1110 22:15:05.535589   64115 round_trippers.go:447]     Content-Type: application/json
I1110 22:15:05.535693   64115 round_trippers.go:447]     Date: Sun, 10 Nov 2019 14:15:05 GMT
I1110 22:15:05.535705   64115 round_trippers.go:447]     Content-Length: 229
{
  "paths": [
    "/apis",
    "/apis/metrics.k8s.io",
    "/apis/metrics.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/metrics",
    "/version"
  ]
}

**Comment by MrD2** [comment]
It is probably an user error.

Check this. https://github.com/helm/charts/tree/master/stable/prometheus-adapter

**Comment by middlestone** [comment]
thanks Diogo, you are right, if using helm to install prometheus-adapter, it has /apis/custom.metrics.k8s.io/v1beta1, but no /apis/metrics.k8s.io/v1beta1, this make me more confused,
which one can decise the prometheus-adapter has /apis/custom.metrics.k8s.io/v1beta1 or not? configmap? or anything else?

# kubectl get -v=8 --raw /api/v1/namespaces/default/services/https:prometheus-adapter:443/proxy/
I1111 20:39:33.287204   17139 loader.go:359] Config loaded from file:  /etc/kubernetes/admin.conf
I1111 20:39:33.288039   17139 round_trippers.go:416] GET https://10.4.5.117:6443/api/v1/namespaces/default/services/https:prometheus-adapter:443/proxy/
I1111 20:39:33.288063   17139 round_trippers.go:423] Request Headers:
I1111 20:39:33.288075   17139 round_trippers.go:426]     User-Agent: kubectl/v1.15.3 (linux/arm64) kubernetes/2d3c76f
I1111 20:39:33.288088   17139 round_trippers.go:426]     Accept: application/json, */*
I1111 20:39:33.355544   17139 round_trippers.go:441] Response Status: 200 OK in 67 milliseconds
I1111 20:39:33.355571   17139 round_trippers.go:444] Response Headers:
I1111 20:39:33.355583   17139 round_trippers.go:447]     Content-Type: application/json
I1111 20:39:33.355594   17139 round_trippers.go:447]     Date: Mon, 11 Nov 2019 12:39:33 GMT
I1111 20:39:33.355605   17139 round_trippers.go:447]     Content-Length: 179
{
  "paths": [
    "/apis",
    "/apis/custom.metrics.k8s.io",
    "/apis/custom.metrics.k8s.io/v1beta1",
    "/healthz",
    "/healthz/ping",
    "/metrics",
    "/version"
  ]

**Comment by middlestone** [comment]
I find the root cause, it is caused by configmap not take effect. thanks Diogo for your help.

**Comment by middlestone** [comment]
I find the root cause, it is caused by configmap not take effect. thanks Diogo for your help.
