### ISSUE TITLE
Can we pass custom labels from hpa itself to adapter queries

### ISSUE THREAD

**Issue by flouthoc** [DirectXMan12/k8s-prometheus-adapter#266]
For instance: I want to scale a hpa on the basis of custom query `base_query{custom_label="label_value"}` and label_value comes from the label on hpa how can i do this.

**Comment by flouthoc** [comment]
@DirectXMan12 ^

**Comment by s-urbaniak** [comment]
@flouthoc i think what you are looking for is implemented in https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/247 which just got merged. once released please feel free to test it out and give feedback :-)
