### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by timchenxiaoyu** [DirectXMan12/k8s-prometheus-adapter#28]
master branch 
make build

vendor/k8s.io/apiserver/pkg/server/routes/openapi.go:35: cannot use c.RegisteredWebServices() (type []*"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".WebService) as type []*"github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".WebService in argument to handler.BuildAndRegisterOpenAPIService
# github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/registry/custom_metrics
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/registry/custom_metrics/reststorage.go:49: cannot use custom_metrics.MetricValue literal (type *custom_metrics.MetricValue) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object in return argument:
	*custom_metrics.MetricValue does not implement "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/registry/custom_metrics/reststorage.go:55: cannot use custom_metrics.MetricValueList literal (type *custom_metrics.MetricValueList) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object in return argument:
	*custom_metrics.MetricValueList does not implement "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/registry/custom_metrics/reststorage.go:98: cannot use *custom_metrics.MetricValueList as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object in return argument:
	*custom_metrics.MetricValueList does not implement "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/registry/custom_metrics/reststorage.go:100: cannot use *custom_metrics.MetricValueList as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object in return argument:
	*custom_metrics.MetricValueList does not implement "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object (wrong type for DeepCopyObject method)
		have DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/runtime".Object
		want DeepCopyObject() "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/runtime".Object
# github.com/directxman12/k8s-prometheus-adapter/pkg/custom-provider
pkg/custom-provider/provider.go:94: cannot use "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time literal (type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".Time in field value
pkg/custom-provider/provider.go:95: cannot use *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/api/resource".NewMilliQuantity(int64(value * 1000), "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/api/resource".DecimalSI) (type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/pkg/api/resource".Quantity) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/metrics/vendor/k8s.io/apimachinery/pkg/api/resource".Quantity in field value
# github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:76: cannot use ws (type *"github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".WebService) as type *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".WebService in argument to versionDiscoveryHandler.AddToWebService
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:248: cannot use restfulListResource(lister, nil, reqScope, false, a.minRequestTimeout) (type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction in argument to metrics.InstrumentRouteFunc
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:251: cannot use rootScopedHandler (type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction in argument to ws.GET(rootScopedPath).To
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:273: cannot use restfulListResource(lister, nil, reqScope, false, a.minRequestTimeout) (type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction in argument to metrics.InstrumentRouteFunc
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:274: cannot use namespacedHandler (type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction in argument to ws.GET(namespacedPath).To
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:297: cannot use restfulListResource(lister, nil, reqScope, false, a.minRequestTimeout) (type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction in argument to metrics.InstrumentRouteFunc
vendor/github.com/kubernetes-incubator/custom-metrics-apiserver/pkg/apiserver/installer/installer.go:298: cannot use namespaceSpecificHandler (type "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".RouteFunction) as type "github.com/directxman12/k8s-prometheus-adapter/vendor/github.com/emicklei/go-restful".RouteFunction in argument to ws.GET(namespaceSpecificPath).To
make: *** [build] 错误 2

**Comment by john-delivuk** [comment]
For anyone who lands here. Answer in this issue. 
https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/3
