### ISSUE TITLE
label name requirements

### ISSUE THREAD

**Issue by emptywee** [DirectXMan12/k8s-prometheus-adapter#29]
Hello.

```
Metrics must have the namespace label to be considered.

For each label on a metric, if that label name corresponds to a Kubernetes resource (like pod or service), the metric will be associated with that resource.
```

Is there any way to configure it? My labels are "kubernetes_namespace", "kubernetes_pod_name" and so forth. Therefore the metrics I need aren't captured by the adapter. I have an existing and long time running prometheus clusters all over the place, it would be potentially a breaking change to relabel everything.

What's the best way to go here?

Thank you!

**Comment by emptywee** [comment]
I was also exploring the way to build it from source and replace the required label names there, but no luck, cannot build it, tried golang 1.6, 1.8 and 1.9 under Ubuntu 16.04 LTS. I am not a developer and probably missing something, but I managed to run glide install correctly, and satisfy all dependencies (maybe not?), so it comes to build phase, and then blows up with a all sort of errors, e.g.:

```
	CGO_ENABLED=0 go build -a -tags netgo -o /build/adapter github.com/directxman12/k8s-prometheus-adapter/cmd/adapter"
# github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/openapi
src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go:88: cannot use config.Info (type *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/vendor/github.com/go-openapi/spec".Info) as type *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/go-openapi/spec".Info in field value
src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go:137: cannot use func literal (type func(string, *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/emicklei/go-restful".Route) (string, []string, error)) as type func(string, *"github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/vendor/github.com/emicklei/go-restful".Route) (string, []string, error) in assignment
src/github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/pkg/server/openapi/openapi.go:142: cannot use func literal (type func(string, string) (string, "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apiserver/vendor/github.com/go-openapi/spec".Extensions)) as type func(string, string) (string, "github.com/directxman12/k8s-prometheus-adapter/vendor/k8s.io/apimachinery/vendor/github.com/go-openapi/spec".Extensions) in assignment

```

And many more...

Is there any chance I can find some help here? :) Thanks in advance.

**Comment by emptywee** [comment]
@luxas I know you managed to build it somehow, maybe you can give me a piece of advice here? Thanks!

**Comment by simonpasquier** [comment]
I tried to reproduce it using master but it works for me. I'm also on Ubuntu 16.04. Not sure what is the issue for you.

```
$ make docker-build
cp deploy/Dockerfile /tmp/tmp.N7fM3UV5CC
cd /tmp/tmp.N7fM3UV5CC && sed -i "s|BASEIMAGE|busybox|g" Dockerfile
docker run -it -v /tmp/tmp.N7fM3UV5CC:/build -v /home/pasquier-s/workspace/goprojects/src/github.com/directxman12/k8s-prometheus-adapter:/go/src/github.com/directxman12/k8s-prometheus-adapter -e GOARCH=amd64 golang:1.8 /bin/bash -c "\
        CGO_ENABLED=0 go build -a -tags netgo -o /build/adapter github.com/directxman12/k8s-prometheus-adapter/cmd/adapter"
docker build -t directxman12/k8s-prometheus-adapter-amd64:latest /tmp/tmp.N7fM3UV5CC
Sending build context to Docker daemon  50.73MB
Step 1/4 : FROM busybox
 ---> 6ad733544a63
Step 2/4 : COPY adapter /
 ---> Using cache
 ---> eb271a1b896b
Step 3/4 : USER 1001:1001
 ---> Using cache
 ---> b9afec329983
Step 4/4 : ENTRYPOINT /adapter
 ---> Using cache
 ---> 8f2caea2a0a3
Successfully built 8f2caea2a0a3
Successfully tagged directxman12/k8s-prometheus-adapter-amd64:latest
sudo rm -r /tmp/tmp.N7fM3UV5CC
```

**Comment by emptywee** [comment]
Thanks @simonpasquier ! Let's assume I get a fresh and clean ubuntu 16.04 and try again from scratch. What actions should I take? What go version and what addons (glide? something else?)?

**Comment by simonpasquier** [comment]
If you have docker installed, the easiest way is simply to run `make docker-build`. Otherwise I'm using go 1.9.2 but 1.8 should work too.

**Comment by emptywee** [comment]
Hmm, it did not really help. What helped me was cleaning up vendor/ subfolder and re-running `glide install -v`. After that I was able to build the adapter. Now I am unlocked to rename the labels it considers to be kubernetes related, and if I get enough knowledge in go, I'd like to make it configurable.

The other problem is that the author claims that the latest release doesn't work with kubernetes 1.7, and requires 1.8. I have 1.7.11, so I either need to get previous' release sources or upgrade my clusters.

**Comment by emptywee** [comment]
Ok, I was able to check out at tag v0.1.0 and build it. I think we can close this issue! Thanks everyone!

**Comment by DirectXMan12** [comment]
Hey, sorry about not responding to this, was out on holiday break.  For posterity, I'd like to address the original question of this PR

> Is there any way to configure it? My labels are "kubernetes_namespace", "kubernetes_pod_name" and so forth. Therefore the metrics I need aren't captured by the adapter. I have an existing and long time running prometheus clusters all over the place, it would be potentially a breaking change to relabel everything.

That might be worth addressing.  Please file an issue about it.  For the moment, the labels we expect follow the Kubernetes instrumentation guidelines (https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md), but it might be worth allowing some sort of prefix or suffix addition as well.

**Comment by emptywee** [comment]
Agreed. Thank you! And Happy New Year!
