### ISSUE TITLE
autoscale  base on memory 

### ISSUE THREAD

**Issue by timchenxiaoyu** [DirectXMan12/k8s-prometheus-adapter#30]
If I want to autoscale base on deployment avg memory used  ,how to do ,does any tutorial?

**Comment by DirectXMan12** [comment]
This is not the correct location to ask this question.  Furthermore, that's covered briefly in the main Kubernetes documentation (https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/).  Notice the beginning of the section where it mentions that besides `cpu`, you can use `memory` as a `Resource` metric.
