### ISSUE TITLE
Metrics not returned via custom.metrics.k8s.io

### ISSUE THREAD

**Issue by hila3000** [DirectXMan12/k8s-prometheus-adapter#307]
Hi,

I’m using prometheus adapter, and I’m trying to get the K8S HPA do its job based on the metric I’ve set prometheus to scrape via the config rules-

data:
  config.yaml: |
    rules:
    - metricsQuery: sum by (kubernetes_pod_name) (hydra_ws_active_conn)
      name:
        as: hydra_ws_active_conn
        matches: ^.*
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      seriesQuery: hydra_ws_active_conn{kubernetes_namespace!="",kubernetes_pod_name!=""}
    - metricsQuery: sum by (app) (hydra_server_semaphore_latency_second_sum{app="agent-gateway-api", kubernetes_namespace="agent-gateway-api"})
      name:
        as: hydra_api_latency
        matches: ^.*
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      seriesQuery: hydra_server_semaphore_latency_second_sum{app="agent-gateway-api", kubernetes_namespace="agent-gateway-api"}

I’m trying to figure out what’s not right with the second query.

The first query is working and I get data-

$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/agent-gateway-api/pods/*/hydra_ws_active_conn" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/agent-gateway-api/pods/%2A/hydra_ws_active_conn"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "agent-gateway-api",
        "name": "agent-gateway-api-ws-868f454554-cbs65",
        "apiVersion": "/v1"
      },
      "metricName": "hydra_ws_active_conn",
      "timestamp": "2020-08-04T11:24:52Z",
      "value": "1273",
      "selector": null
    },
....

When I try the second metric, an empty array is displayed-

$ kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1/namespaces/agent-gateway-api/pods/*/hydra_api_latency" | jq .
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/agent-gateway-api/pods/%2A/hydra_api_latency"
  },
  "items": []
}

From the metrics point, they both get reported, tried to attach images to prove but can't upload images here for some reason. The images show the Grafana explore querying the above metricsQuery queries and shows the same results structure. 

Any idea why do I get an empty array for the second query?

**Comment by charlesparasa** [comment]
I am facing the same issue 
$ kubectl get --raw  /apis/custom.metrics.k8s.io/v1beta1/namespaces/<>/pods/*/Test_ReadyPool_Total_Num_Messages | jq
{
  "kind": "MetricValueList",
  "apiVersion": "custom.metrics.k8s.io/v1beta1",
  "metadata": {
    "selfLink": "/apis/custom.metrics.k8s.io/v1beta1/namespaces/<>/pods/%2A/Test_ReadyPool_Total_Num_Messages"
  },
  "items": [
    {
      "describedObject": {
        "kind": "Pod",
        "namespace": "<>",
        "name": "autoscaling-7c7b45c7c-t7sh9",
        "apiVersion": "/v1"
      },
      "metricName": "Test_ReadyPool_Total_Num_Messages",
      "timestamp": "2020-08-06T09:44:32Z",
      "value": "0",
      "selector": null
    }
  ]
}


Charless-MacBook-Pro:autoscaling charlesparasa$ kubectl describe hpa test-consumer-hpa
Error from server (NotFound): horizontalpodautoscalers.autoscaling "test-consumer-hpa" not found
Charless-MacBook-Pro:autoscaling charlesparasa$ kubectl describe hpa test-consumer-hpa  -n <>
Name:                                           test-consumer-hpa
Namespace:                                      dragonfruit
Labels:                                         <none>
Annotations:                                    kubectl.kubernetes.io/last-applied-configuration:
                                                  {"apiVersion":"autoscaling/v2beta1","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"name":"test-consumer-hpa","namespace":"...
CreationTimestamp:                              Thu, 06 Aug 2020 15:12:29 +0530
Reference:                                      Deployment/test-consumer
Metrics:                                        ( current / target )
  "Test_ReadyPool_Total_Num_Messages" on pods:  <unknown> / 1
Min replicas:                                   2
Max replicas:                                   15
Deployment pods:                                2 current / 0 desired
Conditions:
  Type           Status  Reason               Message
  ----           ------  ------               -------
  AbleToScale    True    SucceededGetScale    the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetPodsMetric  the HPA was unable to compute the replica count: unable to get metric Test_ReadyPool_Total_Num_Messages: no metrics returned from custom metrics API
Events:
  Type     Reason                        Age   From                       Message
  ----     ------                        ----  ----                       -------
  Warning  FailedGetPodsMetric           10s   horizontal-pod-autoscaler  unable to get metric Test_ReadyPool_Total_Num_Messages: no metrics returned from custom metrics API
  Warning  FailedComputeMetricsReplicas  10s   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get pods metric value: unable to get metric Test_ReadyPool_Total_Num_Messages: no metrics returned from custom metrics API

Any quick Help would be appreciated

**Comment by hila3000** [comment]
FYI, This got fixed using this config-
`    - metricsQuery: sum by (kubernetes_pod_name) (hydra:api_latency_seconds:avg)
      name:
        as: hydra_server_api_latency
        matches: ^.*
      resources:
        overrides:
          kubernetes_namespace:
            resource: namespace
          kubernetes_pod_name:
            resource: pod
      seriesQuery: hydra:api_latency_seconds:avg{kubernetes_pod_name!=""}`


hydra:api_latency_seconds:avg is a recording for-
`(avg by (kubernetes_pod_name) (hydra_server_semaphore_latency_second_sum{app="agent-gateway-api"})) / (avg by (kubernetes_pod_name) (hydra_server_semaphore_latency_second_count{app="agent-gateway-api"}))`
