### ISSUE TITLE
Why value of metric end with `m`

### ISSUE THREAD

**Issue by resouer** [DirectXMan12/k8s-prometheus-adapter#32]
I noticed in my own cluster and also luxcas' workshop
```
kubectl ​get ​--raw ​/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/services/sample-metrics-app/http_requests
{"kind":"MetricValueList","apiVersion":"custom.metrics.k8s.io/v1beta1","metadata":{"selfLink":"/apis/custom.metrics.k8s.io/v1beta1/namespaces/default/services/sample-metrics-app/http_requests"},"items":[{"describedObject":{"kind":"Service","name":"sample-metrics-app","apiVersion":"/__internal"},"metricName":"http_requests","timestamp":"2018-01-20T01:54:13Z","value":"866m"}]}
```

My requests total is only 866+, not very sure why the value ends with a `m`? (`"value":"866m"`)

**Comment by simonpasquier** [comment]
If I'm not mistaken, `866m` means `0.866`. Also the metric value isn't a counter but a rate (see https://github.com/DirectXMan12/k8s-prometheus-adapter/blob/master/docs/format.md).

**Comment by DirectXMan12** [comment]
This being the key section of that document:

> When retrieving counter and seconds-counter metrics, the adapter requests the metrics as a rate over the configured amount of time. For metrics with multiple associated resources, the adapter requests the metric aggregated over all non-requested metrics.
