### ISSUE TITLE
Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one.

### ISSUE THREAD

**Issue by anden-dev** [DirectXMan12/k8s-prometheus-adapter#341]
Hello all:

[v0.8.2](https://github.com/DirectXMan12/k8s-prometheus-adapter/releases/tag/v0.8.2) had some unfortunate side-effect on us. The fix #335 broke [kubernetes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets/)

```
Error: Failed to get /openapi/v2 and /swagger.json: Created Component, but require templated one.
```
Only way to get it back to working was reverting to v0.7.0 and deleting the apiservice v1beta1.custom.metrics.k8s.io 

Tickets:
[external-secrets/kubernetes-external-secrets#563](https://github.com/external-secrets/kubernetes-external-secrets/issues/563)
[silasbw/swagger-fluent#55](https://github.com/silasbw/swagger-fluent/issues/55)

The fix should be done by [silasbw/swagger-fluent#55](https://github.com/silasbw/swagger-fluent/issues/55) correct?

**Comment by dgrisonnet** [comment]
Hello @anden-dev,

> The fix should be done by silasbw/swagger-fluent#55 correct?

After going through the various links you provided, I would say so.
So far, we've not seen any other issue with the content of the openapi spec that is served by prometheus-adapter and the error you are seeing seems to induce a bug with the openapi client you are using. My hunch mainly comes from a similar issue already existing there and the fact that the error message your are seeing contains:
> This is a bug. Please report: https://github.com/silasbw/fluent-openapi/issues

Reverting back to v0.7.0 should indeed fix your problem as we only started to serve openapi spec in v0.8.0. However, note that you might stumble upon #254 in the process.

**Comment by anden-dev** [comment]
Thought as much. 

There is a rewrite in go coming anyhow which will also mean a new openapi client [external-secrets/external-secrets](https://github.com/external-secrets/external-secrets).

Thanks for your input.
