### ISSUE TITLE
Update dockerhub image

### ISSUE THREAD

**Issue by parsifal-47** [DirectXMan12/k8s-prometheus-adapter#38]
Hi,
this image got outdated:
https://hub.docker.com/r/directxman12/k8s-prometheus-adapter/

**Comment by DirectXMan12** [comment]
yep, I should have tooling to do this (Travis or somesuch).  Just need to get around to it.

**Comment by parsifal-47** [comment]
thanks a lot!

**Comment by DirectXMan12** [comment]
FYI, it's pushed as `directxman12/k8s-prometheus-adapter-${arch}`, so `directxman12/k8s-prometheus-adapter-amd64`, for instance.
