### ISSUE TITLE
miss LICENSE file

### ISSUE THREAD

**Issue by huxiaoliang** [DirectXMan12/k8s-prometheus-adapter#54]
The best practice that the repository should have `LICENSE `file according to [here ](https://help.github.com/articles/licensing-a-repository/ )so that tells others what they can and can't do with the source code,  it's important to make an informed decision.  

I notice that many files tag `Apache License, Version 2.0` license, but we should make it more clear by `LICENSE `file

**Comment by DirectXMan12** [comment]
closed by #55
