### ISSUE TITLE
Custom Metric self-link for other services ?

### ISSUE THREAD

**Issue by shubhasish** [DirectXMan12/k8s-prometheus-adapter#61]
In [Github page](https://github.com/stefanprodan/k8s-prom-hpa), i found a way to fetch any custom metrics related to Pod. How do i fetch the same for other services such as nodes,replications etc ?

Ex:

`kubectl get --raw "/apis/custom.metrics.k8s.io/v1beta1" | jq .`

>  {
      "name": "namespaces/kube_deployment_status_replicas_updated",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "replicasets.extensions/kube_replicaset_status_observed_generation",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "pods/memory_failcnt",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "daemonsets.extensions/kube_daemonset_status_number_available",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }

What is the self -link for "daemonsets.extensions/kube_daemonset_status_number_available" and replicasets.extensions/kube_replicaset_status_observed_generation ?

**Comment by DirectXMan12** [comment]
so, namespaces is a bit special, but all the namespaced resources follow the same pattern:

`/apis/custom.metrics.k8s.io/v1beta1/namespaces/<namespace>/<resource>.<group>/<name>/<metric>`

So `daemonsets.extensions/kube_daemonset_status_number_available` would be `/apis/custom.metrics.k8s.io/v1beta1/namespaces/<namespace>/daemonsets.extensions/<name>/kube_daemonset_status_number_available`

That make sense?
