### ISSUE TITLE
Add support for External metrics

### ISSUE THREAD

**Issue by jhorwit2** [DirectXMan12/k8s-prometheus-adapter#65]
https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-metrics-not-related-to-kubernetes-objects

**Comment by john-delivuk** [comment]
👍

**Comment by wleese** [comment]
Q: would implementing external metrics here (for Prometheus), exclude the ability to use Stackdriver metrics in a HPA?

**Comment by DirectXMan12** [comment]
you'd have to choose between the two.  Only one thing can be registered to provide a given API.  However, you can choose which to use, even if both provide the API.

**Comment by s-urbaniak** [comment]
closing this out as support for external metrics landed in #146
