### ISSUE TITLE
Configure metric discovery to use same defaults that are in official kubernetes integration config

### ISSUE THREAD

**Issue by huxiaoliang** [DirectXMan12/k8s-prometheus-adapter#71]
reopen issue https://github.com/DirectXMan12/k8s-prometheus-adapter/issues/40

@DirectXMan12 @itskingori I encountered same issue that message "metric xxx not registered" from function QueryForMetric, which caused metric discovery functionality doesn't work by using default prometheus-kubernetes.yml, then I try add --label-prefix=kubernetes_, it still did not work, only patch prometheus-kubernetes.yml diff provide by @itskingori can workaround.

I think the root cause is that you can't use --label-prefix=kubernetes_ to map kubernetes_ namespaces and kubernetes_pod_name` in the same time. (take job_name: 'kubernetes-pods' as an example)

**Comment by DirectXMan12** [comment]
Advanced config will solve this.  Please don't open new issues for existing ones.

**Comment by huxiaoliang** [comment]
@DirectXMan12  so, any plan to get feature `Advanced config` merged? Thanks.
