### ISSUE TITLE
Node level metrics question

### ISSUE THREAD

**Issue by chlung** [DirectXMan12/k8s-prometheus-adapter#74]
Hi,

I have some custom node level metrics.  Can prometheus adapter expose them?  
If I run the following command, I can see some node metrics.
>  kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/ | jq . | grep nodes
"name": "nodes/kube_pod_info",
      "name": "nodes/kube_node_spec_unschedulable",
      "name": "pods/fs_inodes",
      "name": "nodes/kube_node_status_allocatable_memory_bytes",
      "name": "nodes/kube_node_status_condition",
      "name": "nodes/kube_node_created",
      "name": "nodes/kube_node_info",
      "name": "nodes/kube_pod_container_resource_limits_cpu_cores",
      "name": "nodes/kube_node_status_capacity_memory_bytes",
      "name": "nodes/kube_node_status_capacity_pods",
      "name": "nodes/kube_pod_container_resource_requests_cpu_cores",
      "name": "nodes/kube_node_status_allocatable_pods",
      "name": "nodes/kube_node_labels",
      "name": "nodes/kube_pod_container_resource_requests_memory_bytes",
      "name": "pods/fs_inodes_free",
      "name": "nodes/kube_pod_container_resource_limits_memory_bytes",
      "name": "nodes/kube_node_status_allocatable_cpu_cores",
      "name": "nodes/kube_node_status_capacity_cpu_cores",

Then, how can I access them?  
>  kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/nodes/*/kube_pod_container_resource_limits_memory_bytes
Error from server (InternalError): Internal error occurred: unable to list matching resources

Thanks.

**Comment by flunderveiko** [comment]
i have some _namespace_ prefixed metrics and cannot access them, same error.

`
{
      "name": "namespaces/node_memory_PageTables_bytes",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
`

**Comment by larsha** [comment]
Same issue here, still a problem? Seems I can't access any resources. Always `Error from server (InternalError): Internal error occurred: unable to list matching resources`

**Comment by DirectXMan12** [comment]
Can you please post logs from the adapter (at high verbosity) and see if you find any related messages?  Thanks!

**Comment by YaoZengzeng** [comment]
Namespace metic is special, we should get it like :

```
kubectl get --raw /apis/custom.metrics.k8s.io/v1beta1/namespaces/*/metrics/kube_pod_info
```

As for node metric, according to my test, it's ok to get it with the latest adapter code.

However there are very few node metrics with default config, because metrics from node exporter will not be labeled with `node=XXX` and the metrics' name usually begin with `node_`

If we want to get more node metrics, may be we could try to get metrics begin with `node_` and override the `instance` to `node`.

@DirectXMan12 WDYT?

**Comment by s-urbaniak** [comment]
I guess this is covered by #193, now present in the FAQ section.

**Comment by Rich-yi** [comment]
有有效的解决办法了吗
