### ISSUE TITLE
403 forbidden errors in the adapter logs (subjectaccessreviews)

### ISSUE THREAD

**Issue by sreddybr3** [DirectXMan12/k8s-prometheus-adapter#75]
I0606 19:43:11.756324       1 round_trippers.go:436] POST https://100.64.0.1:443/apis/authorization.k8s.io/v1beta1/subjectaccessreviews 201 Created in 3 milliseconds
I0606 19:43:11.756338       1 round_trippers.go:442] Response Headers:
I0606 19:43:11.756342       1 round_trippers.go:445]     Content-Type: application/json
I0606 19:43:11.756346       1 round_trippers.go:445]     Content-Length: 260
I0606 19:43:11.756349       1 round_trippers.go:445]     Date: Wed, 06 Jun 2018 19:43:11 GMT
I0606 19:43:11.756370       1 request.go:836] Response Body: {"kind":"SubjectAccessReview","apiVersion":"authorization.k8s.io/v1beta1","metadata":{"creationTimestamp":null},"spec":{"nonResourceAttributes":{"path":"/","verb":"get"},"user":"system:anonymous","group":["system:unauthenticated"]},"status":{"allowed":false}}
I0606 19:43:11.756432       1 authorization.go:59] Forbidden: "/", Reason: ""
I0606 19:43:11.756644       1 wrap.go:42] GET /: (3.763752ms) 403 [[Go-http-client/2.0] 100.96.152.0:32946]

**Comment by sreddybr3** [comment]
how to set the log level to 2 (instead of default 1)
I notice that adapter uses k8s.io/apiserver -> pkg/util/logs for logging

**Comment by DirectXMan12** [comment]
if you expect to be authenticated as an actual user, make sure that your API server's proxy certificates are set up properly.

> how to set the log level to 2 (instead of default 1)

The prometheus adapter, like much of the rest of kubernetes, uses glog.  The `--v` flag will set the log level.  Try running the adapter with `--help` for more information.
