### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by blackgold** [DirectXMan12/k8s-prometheus-adapter#89]
$ make docker-build
docker run -it -v /home/devendra/gitlab/cim-app-sdk-http/deployment/metrics/certs/k8s-prometheus-adapter:/go/src/github.com/directxman12/k8s-prometheus-adapter -w /go/src/github.com/directxman12/k8s-prometheus-adapter golang:1.10 /bin/bash -c "\
		curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh \
		&& dep ensure -vendor-only -v"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4594  100  4594    0     0  46151      0 --:--:-- --:--:-- --:--:-- 46404
ARCH = amd64
OS = linux
Will install into /go/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.4.1
Fetching https://github.com/golang/dep/releases/tag/v0.4.1..
Fetching https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64..
Setting executable permissions.
Moving executable to /go/bin/dep
(1/62) Wrote github.com/NYTimes/gziphandler@v1.0.1
(2/62) Wrote github.com/elazarl/go-bindata-assetfs@v1.0.0
(3/62) Wrote github.com/evanphx/json-patch@v3.0.0
(4/62) Wrote github.com/beorn7/perks@master
(5/62) Wrote github.com/ghodss/yaml@v1.0.0
(6/62) Wrote github.com/PuerkitoBio/purell@v1.1.0
(7/62) Wrote github.com/go-openapi/jsonpointer@master
(8/62) Wrote github.com/golang/glog@master
(9/62) Wrote github.com/imdario/mergo@v0.3.5
(10/62) Wrote github.com/go-openapi/swag@master
(11/62) Wrote github.com/davecgh/go-spew@v1.1.0
(12/62) Wrote github.com/coreos/go-systemd@v17
(13/62) Wrote github.com/PuerkitoBio/urlesc@master
(14/62) Wrote github.com/go-openapi/jsonreference@master
(15/62) Wrote github.com/google/gofuzz@master
(16/62) Wrote github.com/hashicorp/golang-lru@master
(17/62) Wrote github.com/google/btree@master
(18/62) Wrote github.com/gregjones/httpcache@master
(19/62) Wrote github.com/emicklei/go-restful-swagger12@1.0.1
(20/62) Wrote github.com/pborman/uuid@v1.1
(21/62) Wrote k8s.io/metrics@kubernetes-1.11.0-rc.1
(22/62) Wrote github.com/matttproud/golang_protobuf_extensions@v1.0.1
(23/62) Wrote bitbucket.org/ww/goautoneg@default
(24/62) Wrote github.com/go-openapi/spec@master
(25/62) Wrote github.com/modern-go/reflect2@1.0.0
(26/62) Wrote github.com/coreos/go-semver@v0.2.0
(27/62) Wrote github.com/kubernetes-incubator/custom-metrics-apiserver@master
(28/62) Failed to write golang.org/x/sys@master
(29/62) Failed to write golang.org/x/time@master
(30/62) Failed to write github.com/googleapis/gnostic@v0.2.0
(31/62) Failed to write github.com/inconshreveable/mousetrap@v1.0
(32/62) Failed to write google.golang.org/grpc@v1.13.0
(33/62) Failed to write github.com/prometheus/client_golang@v0.8.0
(34/62) Failed to write github.com/json-iterator/go@1.1.3
(35/62) Failed to write github.com/peterbourgon/diskv@v2.0.1
(36/62) Failed to write gopkg.in/yaml.v2@v2.2.1
(37/62) Failed to write github.com/petar/GoLLRB@master
(38/62) Failed to write github.com/modern-go/concurrent@1.0.3
(39/62) Failed to write github.com/emicklei/go-restful@v2.7.1
(40/62) Failed to write golang.org/x/text@v0.3.0
(41/62) Failed to write github.com/golang/protobuf@v1.1.0
(42/62) Failed to write github.com/coreos/etcd@v3.3.8
(43/62) Failed to write k8s.io/api@kubernetes-1.11.0-rc.1
(44/62) Failed to write github.com/gogo/protobuf@v1.0.0
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/sys: remote repository at https://go.googlesource.com/sys does not exist, or is inaccessible: no data returned from ls-remote
make: *** [vendor] Error 1

**Comment by DirectXMan12** [comment]
I've seen a similar error in travis on another package.  It seems like a rate-limit issue.  Please try again at another time.  I've also checked the vendor directory in, so this shouldn't auto-run any more.
