### ISSUE TITLE
Images and a chart

### ISSUE THREAD

**Issue by plumdog** [DirectXMan12/k8s-prometheus-adapter#90]
Now that I've got k8s-prometheus-adapter up and working, I am utterly convinced of its necessity.

However, getting it working wasn't straightforward as the linked example is a bit old, and I was lacking in some prometheus and kubernetes-investigation skills that I have learned along the way.

I think two things would help to make k8s-prometheus-adapter easier to get going with:

- Official images built and made available on quay/dockerhub/other.
- A helm chart added to https://github.com/kubernetes/charts

This would give any docs/walkthroughs something to work from (eg, "this walkthrough uses chart version x and image version y") to reduce any version-related snafus.

Given that I think I have the basis of a working chart (I started with https://github.com/madeden/charts/tree/master/custom-metrics-apiserver and have tinkered), I think I can be useful there. Also, I'm keen to document my findings somewhere useful, probably by adding bits to the walkthrough. (In particular, how to get this working with metrics from the nginx-ingress-controller).

However, without images, the above becomes rather tricky. I notice that https://hub.docker.com/r/directxman12/k8s-prometheus-adapter-amd64/tags/ does have a quite recent "latest", but nothing else. Even just tagging with the Git SHA would be super useful.

Once those images exist, I'd been keen to contribute a chart to the charts repo, and update the walkthrough accordingly (for anyone using helm).

**Comment by DirectXMan12** [comment]
There are official images built by the CI (`directxman12/k8s-prometheus-adapter-${ARCH}`), but there was a hiccup in that (as you noticed) due to an issue with what appeared to be github rate limiting.  I'll tag another release to trigger another tag.

I'd be happy to have an official chart submitted, let me know if you submit a PR.  I'd also *love* any contributions to the walkthrough :-).

**Comment by steven-sheehy** [comment]
I've submitted a Helm chart to to charts/incubator: https://github.com/helm/charts/pull/7159

**Comment by steven-sheehy** [comment]
@DirectXMan12 I think this issue can be closed now. prometheus-adapter is now in the official chart repository under [stable/prometheus-adapter](https://github.com/helm/charts/tree/master/stable/prometheus-adapter).

**Comment by plumdog** [comment]
Amazing stuff.

Yup, I agree this can now be closed.

Perhaps worth adding a link to that in the docs somewhere, but I guess this issue sort of achieves that anyway.
